### ISSUE TITLE
Auto shear/milk doesn't consider animal's Golden Animal Cracker

### ISSUE THREAD

**Issue by BananaFruit476** [Hackswell/GloryOfEfficiency#10]
The auto shear/milk function only harvests 1 produce, not 2 when the animal has been given a [Golden Animal Cracker](https://stardewvalleywiki.com/Golden_Animal_Cracker)

**Comment by Hackswell** [comment]
Sorry!  I've been working on getting as much "existing" working before handling more of the new 1.6 specific things.   I'll be sure to check this out for ALPHA5!

**Comment by Hackswell** [comment]
This should be fixed in ALPHA 6.
