### ISSUE TITLE
Auto Fish ignore the treasure & wrong HUD for treasure time

### ISSUE THREAD

**Issue by leatrise** [Hackswell/GloryOfEfficiency#11]
1. HUD for treasure incoming time display wrongly:
![image](https://github.com/Hackswell/JoysOfEfficiency/assets/87349392/295ef395-cd77-4929-9131-26fbfc640796)
it shows for the time for millisecond instand of second.

2. treasure ignorance:
![image](https://github.com/Hackswell/JoysOfEfficiency/assets/87349392/f7c0d58f-46dc-4525-aeae-473ebe66b21f)
the auto fish just concentrate on catch the fish!! it would not grab the treasure!!!

**Comment by Hackswell** [comment]
Haven't worked on auto-fishing yet.  Just barely got the probabilities box working again.  Scheduled for ALPHA5.

**Comment by Hackswell** [comment]
Possibly fixed with Sandman534's pull request.  Fix should be in ALPHA 4.
