### ISSUE TITLE
Fishing Hud Log Spam and Red Circles

### ISSUE THREAD

**Issue by Sandman534** [Hackswell/GloryOfEfficiency#12]
I have several mods installed that add new fishing stuff. SVE, Ridgeside, Lunna and East Scarp. Whenever I use the Fish HUD, depending on where I am at a get several red circles and 0.0% catch rate. On top of that every time I fish my SMAPI log spams a crazy amount of data constantly.

**Comment by Exaxxion** [comment]
Bug introduced with the fishing features and (purported) fixes in Alpha 3. Nearly all of the recent issues on the tracker are related to it (#2, #9, #11, #12 (yours), #13).

**Comment by Sandman534** [comment]
It looks like a whole bunch of weird IDs are coming in when grabing the fish information. Don't know what the fix is, but thats why there are so many circles. The log spam just comes from the amount of data it parses through. Probably just need to comment out all the logging as I imagine most of it was put in to debug rather than be for the end user

**Comment by Sandman534** [comment]
Submitted a PR that fixes this issue amongst many other I encountered. Also removes all the log spam

**Comment by Hackswell** [comment]
Thanks!  I've pulled, and will test for ALPHA4.

**Comment by Hackswell** [comment]
Pulled into develop16 branch for ALPHA 4.
