### ISSUE TITLE
The location of Fish information HUD 

### ISSUE THREAD

**Issue by fjf010223** [Hackswell/GloryOfEfficiency#14]
The location of Fish information HUD will change due to  UI Scale and Zoom Level, Only when 100% is correct
![9d1f92123859f6dc0a5bd4d232a33a41](https://github.com/Hackswell/JoysOfEfficiency/assets/24584711/5f254081-3d00-4eb5-9b7d-52a33933bbf9)
![a301d08805334d0f24cc93d091a7d7e2](https://github.com/Hackswell/JoysOfEfficiency/assets/24584711/355966b3-e563-4522-a0b3-bff6f9142659)
![08375de149c7e6f792e410a833b33510](https://github.com/Hackswell/JoysOfEfficiency/assets/24584711/28ba32cb-7e40-409a-8fc7-0ee4c0d19fe8)

**Comment by Hackswell** [comment]
Thank you for your report!   Unfortunately, I am working mostly on fixing horribly broken things or things that should work.  This is UI (User Interface), so I will get to it once JoE works more completely.  Thank you for your patience.
