### ISSUE TITLE
Fish information is not accurate

### ISSUE THREAD

**Issue by GeekPorridge** [Hackswell/GloryOfEfficiency#16]
The fishing information is not accurate. For example, fishing in the forest in spring will show that there are no fish in the lake currently. I remember that this problem will not exist in 1.5. If you see it, please fix it.
<img width="1280" alt="09361925eb1e4fac5289616d772a116" src="https://github.com/Hackswell/JoysOfEfficiency/assets/87751278/53a169e2-3cb4-4fca-802e-9d2eccb42f63">
<img width="1280" alt="12c3f0506333efa2db7c3632c7540ef" src="https://github.com/Hackswell/JoysOfEfficiency/assets/87751278/923642d7-811b-4b5e-be8b-2d94fc042fc0">

**Comment by Hackswell** [comment]
I am in the middle of converting from a static list of probabilities into automatically pulling lists from the SdV API.  Unfortunately, some of the areas don't return information properly for the sewers and in the mines.  I have no clue why it doesn't return me any data!  I'm still working on it!

**Comment by GeekPorridge** [comment]
OK, thanks

**Comment by Hackswell** [comment]
Please check to see if this is fixed once ALPHA 4 comes out.  Sandman534 did heaps of work in this area of the code.

**Comment by GeekPorridge** [comment]
When is it expected to be released?

**Comment by Hackswell** [comment]
> When is it expected to be released?

Just released it.
