### ISSUE TITLE
Fishing showing red circles with a line through them on probability window - SVE/Capitalist Dream Farm 2

### ISSUE THREAD

**Issue by etmoonshade** [Hackswell/GloryOfEfficiency#19]
Edit: Version is 1.5.0Alpha3. Forgot to put that in. 😛 

I suspect it's a modded issue, but I'm not sure which mod it's from. See below:
![image](https://github.com/Hackswell/JoysOfEfficiency/assets/279491/87c1bbd6-b660-453d-bfe3-7e78d1b3992b)

Also, uh. Each cast generates about 11k lines of logging. I was wondering why I couldn't find the start of the logging in the SMAPI window. o.o

See attached file. Kind of excessive, really. 😆 
[JoEAlphaLog20240414.txt](https://github.com/Hackswell/JoysOfEfficiency/files/14971764/JoEAlphaLog20240414.txt)

Note that the log is from a different cast than the one pictured, and actually in a different place on the CDF, but it exhibits the same behavior - looks like all the water on the farm does the same thing.

Another notable thing is that the same behavior shows on another modded map from SVE, the bridge to Grampleton:
![image](https://github.com/Hackswell/JoysOfEfficiency/assets/279491/af7e33d1-4924-4688-8a09-d5aabd4c371b)

Based on this, it may be a problem with how it's reading modded data in general, though as you can see above, it actually does show _some_ of the modded fish.

**Comment by Hackswell** [comment]
Please check to see if this is fixed once ALPHA 4 comes out. Sandman534 did heaps of work in this area of the code.

**Comment by etmoonshade** [comment]
This does appear to be fixed in Alpha 5 at least (sorry, skipped 4 lol,) so this can probably be closed. Sorry for the late update. :)
