### ISSUE TITLE
Fishing probabilities throw error

### ISSUE THREAD

**Issue by Mythos** [Hackswell/GloryOfEfficiency#33]
Hey there,
unfortunately, every time I fish, an exception is being logged. It is related to the fishing probabilities window, even though I have it disabled.

https://smapi.io/log/d1a204653dad47bb9f6256af16892b13

**Comment by Hackswell** [comment]
Mythos: has this issue been resolved yet in GoE 1.0.0?

**Comment by Mythos** [comment]
Just did a quick test with the window enabled and disabled.
Probability window works fine for me, no exception has been logged.

Thanks for the fix!

/closed
