### ISSUE TITLE
Auto Pet

### ISSUE THREAD

**Issue by mttmmj** [Hackswell/GloryOfEfficiency#4]
I used unbalanced mode, however, it didn't pet all my animal automaticaly, I am sure I was near my sheep, it just pet part of my animals, and pet the left part after a long time. 
Thanks lot for your work!

**Comment by Hackswell** [comment]
Updated to Update every Nth Tick.   If BalancedMod is TRUE, NthTick is set to 60 (60 ticks ~= 1 second).  If FALSE, then NthTick is set to 15 (0.25 seconds).  This can be edited in the config.json.  Smaller numbers are faster, but will tax your computer more.
