### ISSUE TITLE
Cannot auto-harvest carrots

### ISSUE THREAD

**Issue by Hackswell** [Hackswell/GloryOfEfficiency#7]
Cannot auto-harvest carrots

reported by: [wandeng](https://www.nexusmods.com/users/87282053)

**Comment by peizp** [comment]
me too

**Comment by Hackswell** [comment]
Stems from any new crop in 1.6 being a string and not a number.  Will be fixed in ALPHA 4.
You will probably need to update your config.json if you have any harvest exceptions, and put each exception in quotation marks to "string-ify" them.

Thank you for reporting.

**Comment by Hackswell** [comment]
Fixed in develop16 branch for ALPHA 4.
